[project]
name = "epi-crawl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi-mcp>=0.1.4",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "firecrawl>=1.15.0",
    "beautifulsoup4>=4.13.3",
    "aiohttp>=3.11.16",
    "pandas>=2.2.3",
    "requests>=2.31.0",
    "pymongo>=4.12.0",
    "dnspython>=2.7.0"
]
